# Generated by Django 5.0.3 on 2025-05-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
